///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
///* Header for class se_sics_hop_metadata_ndb_JniNdbEventStreaming */
//
//#ifndef _Included_se_sics_hop_metadata_ndb_JniNdbEventStreaming
//#define _Included_se_sics_hop_metadata_ndb_JniNdbEventStreaming
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     se_sics_hop_metadata_ndb_JniNdbEventStreaming
// * Method:    startEventAPISession
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_se_sics_hop_metadata_ndb_JniNdbEventStreaming_startEventAPISession(
//		JNIEnv *, jobject);
//
///*
// * Class:     se_sics_hop_metadata_ndb_JniNdbEventStreaming
// * Method:    closeEventAPISession
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_se_sics_hop_metadata_ndb_JniNdbEventStreaming_closeEventAPISession(
//		JNIEnv *, jobject);
//
//#ifdef __cplusplus
//}
//#endif
//#endif

#include <jni.h>
/* Header for class NdbEventStreaming */

#ifndef _Included_NdbEventStreaming
#define _Included_NdbEventStreaming
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NdbEventStreaming
 * Method:    startEventAPISession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_se_sics_hop_metadata_ndb_JniNdbEventStreaming_startEventAPISession(
		JNIEnv *, jobject);

/*
 * Class:     NdbEventStreaming
 * Method:    closeEventAPISession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_se_sics_hop_metadata_ndb_JniNdbEventStreaming_closeEventAPISession(
		JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
